### ISSUE TITLE
her şey çok güzel

### ISSUE THREAD

**Issue by goeksu** [bubirwebsitesi/bubirwebsitesi.github.io#1]
ama yazıcıoğlu işhanı yerine süzer plaza yazmalıydınız..

**Comment by rojenzaman** [comment]
Teşekkürler, cümle önerinize göre güncellendi. Artık şu şekilde:

> Senin web sitesi diye yaptığın şey Süzer Plaza gibi, bir oda servisi eksik. Utanmasan arka planı altın varaklardan yapacaksın.
